# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sec-api-io',
                'doc_host': 'https://Elijas.github.io',
                'git_url': 'https://github.com/Elijas/sec-api-io',
                'lib_path': 'sec_api_io'},
  'syms': {'sec_api_io.core': {'sec_api_io.core.foo': ('core.html#foo', 'sec_api_io/core.py')}}}
